---

jobs:
  - interval: 3600
    run: getConsumablesStatus()

  - interval: 300
    run: getCleaningHistory()

  - interval: 60
    run: getStatus()

  - interval: 5
    if:
      - ${Properties.selfObjectName}.delayedCleanup is true
      - House.closedDoors is false
      - House.closedDoors.timeSince > 300
    run:
      - ${Properties.selfObjectName}.start()
      - SystemNotify.send('Started delayed cleaning')
    set:
      ${Properties.selfObjectName}.delayedCleanup: 'false'
