---  # Known objects

# EXAMPLE:
#
# Livingroom-Button:
#   base: !import Module.XiaomiButton
#   with:
#     mqtt-topic: zigbee2mqtt/button-2
#
# Reading-Light:
#   base: !import Module.YeelightBulb
#   with:
#     ip: 192.168.0.130


# SYSTEM NOTIFIFCATIONS - SLACK

# SystemNotify:
#   base: !import Module.Slack
#   with:
#     endpoint: YOUR_SLACK_WEBHOOK_ENDPOINT

# SystemWarn:
#   base: !import Module.Slack
#   with:
#     endpoint: YOUR_SLACK_WEBHOOK_ENDPOINT
