---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    illuminance: ${PARAMS.illuminance}
    occupancy: ${PARAMS.occupancy}
    no_occupancy_since: ${PARAMS.no_occupancy_since}
    linkquality: ${PARAMS.linkquality}
    battery: ${PARAMS.battery}
    voltage: ${PARAMS.voltage}
