---

cmd: 'mosquitto_pub -h mqtt -t "snapcast/tx" -m'

functions:

  getStatus():
    run: "${cmd} '{\"id\":8,\"jsonrpc\":\"2.0\",\"method\":\"Client.GetStatus\",\"params\":{\"id\":\"${Properties.id}\"}}'"

  setLatency(latency):
    run: "${cmd} '{\"id\":7,\"jsonrpc\":\"2.0\",\"method\":\"Client.SetLatency\",\"params\":{\"id\":\"${Properties.id}\",\"latency\":${ARGS.latency}}}'"
    set:
      latency: ${ARGS.latency}

  setName(name):
    run: "${cmd} '{\"id\":7,\"jsonrpc\":\"2.0\",\"method\":\"Client.SetName\",\"params\":{\"id\":\"${Properties.id}\",\"name\":\"${ARGS.name}\"}}'"
    set:
      name: ${ARGS.name}

  setVolume(volume):
    run: "${cmd} '{\"id\":\"8\",\"jsonrpc\":\"2.0\",\"method\":\"Client.SetVolume\",\"params\":{\"id\":\"${Properties.id}\",\"volume\":{\"percent\":${ARGS.volume}}}}'"
    set:
      volume: ${ARGS.volume}

  mute():
    run: "${cmd} '{\"id\":\"8\",\"jsonrpc\":\"2.0\",\"method\":\"Client.SetVolume\",\"params\":{\"id\":\"${Properties.id}\",\"volume\":{\"muted\":true}}}'"
    set:
      muted: 'true'

  unmute():
    run: "${cmd} '{\"id\":\"8\",\"jsonrpc\":\"2.0\",\"method\":\"Client.SetVolume\",\"params\":{\"id\":\"${Properties.id}\",\"volume\":{\"muted\":false}}}'"
    set:
      muted: 'false'

  toggle():
    runIf:
      - ${Properties.selfObjectName}.muted is not true
    runFunctions:
      - ${Properties.selfObjectName}.mute()
    runFunctionsElse:
      - ${Properties.selfObjectName}.unmute()

  on():
    runFunctions:
      - ${Properties.selfObjectName}.unmute()

  off():
    runFunctions:
      - ${Properties.selfObjectName}.mute()



  increaseVolume():
    runFunctions:
      - ${Properties.selfObjectName}.increaseVolume1step()
      - ${Properties.selfObjectName}.increaseVolume2steps()
      - ${Properties.selfObjectName}.increaseVolume3steps()

  increaseVolume1step():
    runIf:
      - ${Properties.selfObjectName}.volume <= 20
    runElseIf:
      - ${Properties.selfObjectName}.volume is 99
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume + 1')

  increaseVolume2steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 20
      - ${Properties.selfObjectName}.volume <= 50
    runElseIf:
      - ${Properties.selfObjectName}.volume is 98
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume + 2')

  increaseVolume3steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 50
      - ${Properties.selfObjectName}.volume <= 97
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume + 3')



  decreaseVolume():
    runFunctions:
      - ${Properties.selfObjectName}.decreaseVolume1step()
      - ${Properties.selfObjectName}.decreaseVolume2steps()
      - ${Properties.selfObjectName}.decreaseVolume3steps()
      - ${Properties.selfObjectName}.decreaseVolume4steps()
      - ${Properties.selfObjectName}.decreaseVolume5steps()

  decreaseVolume1step():
    runIf:
      - ${Properties.selfObjectName}.volume > 0
      - ${Properties.selfObjectName}.volume <= 20
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume - 1')

  decreaseVolume2steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 20
      - ${Properties.selfObjectName}.volume <= 40
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume - 2')

  decreaseVolume3steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 40
      - ${Properties.selfObjectName}.volume <= 60
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume - 3')

  decreaseVolume4steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 60
      - ${Properties.selfObjectName}.volume <= 80
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume - 4')

  decreaseVolume5steps():
    runIf:
      - ${Properties.selfObjectName}.volume > 80
    runFunctions:
      - ${Properties.selfObjectName}.setVolume('${Properties.selfObjectName}.volume - 5')
