---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.params.id}: ${Properties.id}
  - ${PARAMS.result.client.id}: ${Properties.id}

# Take the action param from the event param
actionParam: ${PARAMS.method}

# Known actions and what variables are set by them
actions:
  all:
    name: ${PARAMS.result.client.config.name}
    latency: ${PARAMS.result.client.config.latency}
    muted: ${PARAMS.result.client.config.volume.muted}
    volume: ${PARAMS.result.client.config.volume.percent}
    connected: ${PARAMS.result.client.connected}
    host_arch: ${PARAMS.result.client.host.arch}
    host_ip: ${PARAMS.result.client.host.ip}
    host_mac: ${PARAMS.result.client.host.mac}
    host_name: ${PARAMS.result.client.host.name}
    host_os: ${PARAMS.result.client.host.os}
    snapclient_name: ${PARAMS.result.client.snapclient.name}
    snapclient_protocolVersion: ${PARAMS.result.client.snapclient.protocolVersion}
    snapclient_version: ${PARAMS.result.client.snapclient.version}

  Client.OnConnect:
    name: ${PARAMS.params.client.config.name}
    latency: ${PARAMS.params.client.config.latency}
    muted: ${PARAMS.params.client.config.volume.muted}
    volume: ${PARAMS.params.client.config.volume.percent}
    connected: ${PARAMS.params.client.connected}
    host_arch: ${PARAMS.params.client.host.arch}
    host_ip: ${PARAMS.params.client.host.ip}
    host_mac: ${PARAMS.params.client.host.mac}
    host_name: ${PARAMS.params.client.host.name}
    host_os: ${PARAMS.params.client.host.os}
    snapclient_name: ${PARAMS.params.client.snapclient.name}
    snapclient_protocolVersion: ${PARAMS.params.client.snapclient.protocolVersion}
    snapclient_version: ${PARAMS.params.client.snapclient.version}

  Client.OnDisconnect:
    name: ${PARAMS.params.client.config.name}
    latency: ${PARAMS.params.client.config.latency}
    muted: ${PARAMS.params.client.config.volume.muted}
    volume: ${PARAMS.params.client.config.volume.percent}
    connected: ${PARAMS.params.client.connected}
    host_arch: ${PARAMS.params.client.host.arch}
    host_ip: ${PARAMS.params.client.host.ip}
    host_mac: ${PARAMS.params.client.host.mac}
    host_name: ${PARAMS.params.client.host.name}
    host_os: ${PARAMS.params.client.host.os}
    snapclient_name: ${PARAMS.params.client.snapclient.name}
    snapclient_protocolVersion: ${PARAMS.params.client.snapclient.protocolVersion}
    snapclient_version: ${PARAMS.params.client.snapclient.version}

  Client.OnVolumeChanged:
    muted: ${PARAMS.params.volume.muted}
    volume: ${PARAMS.params.volume.percent}

  Client.OnLatencyChanged:
    latency: ${PARAMS.params.latency}

  Client.OnNameChanged:
    name: ${PARAMS.params.name}
