---

status:
  Disconnect notification:
    if:
      - this.status is 'offline'
      - this.status.previousValue in ('on','off')
    run:
      - SystemWarn.send('A light is offline!')
      - SystemNotify.send('A light is offline!')

  Reconnect notification:
    if:
      - this.status in ('on','off')
      - this.status.previousValue is 'offline'
    run:
      - SystemWarn.send('A light is online')
      - SystemNotify.send('A light is online')

  Reconnect action:
    if:
      - this.status is 'on'
      - this.status.previousValue is 'offline'
    run:
      - this.brightness('25')
      - System.sleep('0.4')
      - this.brightness('100')
