---

status:
  Disconnect notification - ${Properties.selfObjectName}:
    if:
      - this.status is 'offline'
      - this.status.previousValue in ('on','off')
    run:
      - SystemWarn.send('${Properties.selfObjectName} is offline!')
      - SystemNotify.send('${Properties.selfObjectName} is offline!')

  Reconnect notification - ${Properties.selfObjectName}:
    if:
      - this.status in ('on','off')
      - this.status.previousValue is 'offline'
    run:
      - SystemWarn.send('${Properties.selfObjectName} is online')
      - SystemNotify.send('${Properties.selfObjectName} is online')

  Reconnect action - ${Properties.selfObjectName}:
    if:
      - this.status is 'on'
      - this.status.previousValue is 'offline'
    run:
      - this.brightness('25')
      - System.sleep('0.4')
      - this.brightness('100')
