---

emergency-voltage: 170
critical-voltage: 190
critical-to-emergency-delay: 5
secondary-warn-object: NONE
socket-1: NONE
socket-2: NONE
socket-3: NONE
socket-4: NONE
socket-5: NONE
socket-6: NONE
socket-7: NONE
socket-8: NONE
socket-9: NONE
