---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    illuminance: ${PARAMS.illuminance}
    occupancy: ${PARAMS.occupancy}
    no_occupancy_since: ${PARAMS.no_occupancy_since}
    linkquality: ${PARAMS.linkquality}
    battery: ${PARAMS.battery}
    voltage: ${PARAMS.voltage}
    last-input-time: foo

# Params are not rewritten in the DB if the value isn't changed.
# This allows them to be written anyway.
alwaysSetWhenReceived:
  - last-input-time
