---

cmd: 'mosquitto_pub -h localhost -t "${Properties.mqtt-topic}/rx" -m'

functions:

  on():
    run: '${cmd} on'

  off():
    run: '${cmd} off'

  toggle():
    run: '${cmd} toggle'

  brightness(value):
    run: '${cmd} "brightness ${ARGS.value}"'
