---

cmd: 'mosquitto_pub -h localhost -t "${Properties.mqtt-topic}/rx" -m'

functions:

  on():
    run: '${cmd} on'

  off():
    run: '${cmd} off'

  toggle():
    run: '${cmd} toggle'

  brightness(value):
    run: '${cmd} "brightness ${ARGS.value}"'

  checkAway():
    runIf:
      - ${Properties.room}.lastMotion.timeSince >= 600
      - House.lastMotion.timeSince < 600
      - ${Properties.selfObjectName}.status is not off
    runFunctions:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('${Properties.selfObjectName} OFF (Away)')
      - SystemWarn.send('${Properties.selfObjectName} OFF (Away)')

  checkSleeping():
    runIf:
      - House.sleeping is true
      - House.sleeping.timeSince >= 600
      - ${Properties.selfObjectName}.status is not off
    runFunctions:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('${Properties.selfObjectName} OFF (Sleeping)')
      - SystemWarn.send('${Properties.selfObjectName} OFF (Sleeping)')
