version: '2.2'

services:

  mqtt:
    image: eclipse-mosquitto:1.6.9
    container_name: smarthome-mqtt
    restart: always
    volumes:
      - ./data/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 1883:1883
      - 1884:1884
    mem_limit: 512M
    memswap_limit: 0M
    cpu_shares: 2048

  # mqtt-gaming:
  #   image: eclipse-mosquitto:1.6.9
  #   container_name: smarthome-mqtt-gaming
  #   restart: always
  #   volumes:
  #     - ./data/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  #   ports:
  #     - 12345:1883
  #     - 12346:1884
  #   mem_limit: 512M
  #   memswap_limit: 0M
  #   cpu_shares: 2048

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.25.2
    # image: koenkk/zigbee2mqtt:1.18.1
    container_name: smarthome-zigbee2mqtt
    restart: always
    depends_on:
      - mqtt
    devices:
      - $DEVICE_ZIGBEE:/dev/ttyACM0
    volumes:
      - ./data/zigbee2mqtt:/app/data
    environment:
      - TZ=$TIMEZONE
    mem_limit: 512M
    memswap_limit: 0M
    cpu_shares: 2048

  db:
    image: mariadb:10.2.32
    container_name: smarthome-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=$MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
    mem_limit: 1G
    memswap_limit: 0M
    cpu_shares: 2048

  python-miio2mqtt:
    image: 192.168.0.100:5000/python-miio2mqtt:1.0.0
    container_name: smarthome-service-python-miio2mqtt
    restart: always
    build:
      context: ./services/python-miio2mqtt
    # network_mode: host
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST=mqtt
      - MQTT_TOPIC=service/python-miio
    mem_limit: 256M
    memswap_limit: 0M
    cpu_shares: 2048

  app:
    image: 192.168.0.100:5000/smarthome:1.0.0
    container_name: smarthome-app
    build:
      context: ./app
      args:
        DOCKER_TIMEZONE: $TIMEZONE
    depends_on:
      - mqtt
      - db
      - zigbee2mqtt
    restart: always
    devices:
      - $DEVICE_CEC:/dev/ttyACM0
    # network_mode: host
    ports:
      - $PORT_WEB:80
    volumes:
      - ./data/app:/app/data
      # TODO: remove mounts - used for development
      - ./app/app/modules/core/src:/app/modules/core/src
      - ./app/app/web/Core:/app/web/Core
      - ./app/app/web/UI:/app/web/UI
      - ./app/app/web/res:/app/web/res
      - ./tmp/app/go:/root/go
      - ./tmp/app/go-build:/root/.cache/go-build
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=$MYSQL_HOST
      - APP_ENV=$APP_ENV
      - HOST_IP=$HOST_IP
    mem_limit: 1G
    memswap_limit: 0M
    cpu_shares: 2048
