---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}/tx

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    device: ${PARAMS.device}

# Params are not rewritten in the DB if the value isn't changed.
# This allows them to be written anyway.
alwaysSetWhenReceived:
  - device
