---

# cmd: 'mosquitto_pub -h mqtt -t "${Properties.mqtt-topic}/cmd" -m'

functions:

  checkStatus():
    run: ping -W 1 -c 1 ${Properties.ip} | grep '1 received' | wc -l
    if: ${RESPONSE.output} is 1
    set:
      status: 'on'
    elseSet 2nd time:
      status: 'off'
