---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:

  ${Properties.mqtt-topic}:
    activity: ${PARAMS.activity}
    battery: ${PARAMS.battery}
    charging: ${PARAMS.charging}
    temperature: ${PARAMS.temperature}
    lux: ${PARAMS.lux}
    displays: ${PARAMS.displays}
    brightness: ${PARAMS.brightness}
    volume: ${PARAMS.volume}
    status: ${PARAMS.status}
    locked: ${PARAMS.locked}
    call: ${PARAMS.call}
    working: ${PARAMS.working}
    playing: ${PARAMS.playing}
    playing-artist: ${PARAMS.playing-artist}
    playing-title: ${PARAMS.playing-title}
