--- # Do stuff when certain variables are changed

${Properties.selfObjectName}.battery:
  Low battery warning - ${Properties.selfObjectName}:
    if: this < 10
    run:
      - SystemWarn.send('${Properties.selfObjectName} has low battery!')
      - SystemNotify.send('${Properties.selfObjectName} has low battery!')

${Properties.selfObjectName}.call:

  Start - ${Properties.selfObjectName}:
    if: this is true
    run: SystemNotify.send('Starting call - ${Properties.selfObjectName}')

  End - ${Properties.selfObjectName}:
    if: this is false
    run: SystemNotify.send('Call ended - ${Properties.selfObjectName}')

${Properties.selfObjectName}.status:

  ON - ${Properties.selfObjectName}:
    if: this is on
    run: SystemNotify.send('${Properties.selfObjectName} ON')

  OFF - ${Properties.selfObjectName}:
    if: this is off
    run: SystemNotify.send('${Properties.selfObjectName} OFF')
    set:
      ${Properties.selfObjectName}.locked: 'true'
      ${Properties.selfObjectName}.charging: 'false'
      ${Properties.selfObjectName}.call: 'false'

${Properties.selfObjectName}.locked:

  Locked - ${Properties.selfObjectName}:
    if: this is true
    run: SystemNotify.send('${Properties.selfObjectName} is locked')

  Unlocked - ${Properties.selfObjectName}:
    if: this is false
    run: SystemNotify.send('${Properties.selfObjectName} is unlocked')
    set:
      ${Properties.selfObjectName}.status: 'on'

${Properties.selfObjectName}.charging:

  Charging - ${Properties.selfObjectName}:
    if: this is true
    run: SystemNotify.send('${Properties.selfObjectName} is charging')

  Discharging - ${Properties.selfObjectName}:
    if: this is false
    run: SystemNotify.send('${Properties.selfObjectName} is discharging')
