---

${Properties.selfObjectName}.battery:
  Low battery - ${Properties.selfObjectName}:
    if:
      - this <= 40
      - this < ${Properties.selfObjectName}.battery.previousValue
    run:
      - SystemWarn.send('${Properties.selfObjectName} has this.battery% battery left!')
      - SystemNotify.send('${Properties.selfObjectName} has this.battery% battery left!')

${Properties.light-sensor}.illuminance_lux:
  Sync illuminance - ${Properties.selfObjectName}:
    set:
      ${Properties.selfObjectName}.illuminance: ${Properties.light-sensor}.illuminance_lux

${Properties.motion-sensor}.occupancy:
  Sync occupancy - ${Properties.selfObjectName}:
    set:
      ${Properties.selfObjectName}.occupancy: ${Properties.motion-sensor}.occupancy

${Properties.motion-sensor}.no_occupancy_since:
  Sync no_occupancy_since - ${Properties.selfObjectName}:
    set:
      ${Properties.selfObjectName}.no_occupancy_since: ${Properties.motion-sensor}.no_occupancy_since
