---

cmdStart: "mosquitto_pub -h localhost -t \"broadlink2mqtt/send\" -m '{\"ip\": \"${Properties.ip}\",\"type\": \"${Properties.type}\",\"mac\": \"${Properties.mac}\",\"mode\": \""
cmdMid: "\",\"packet\": \""
cmdEnd: "\"}'"

functions:

  sendIrPacket(packet):
    run: ${cmdStart}ir${cmdMid}${ARGS.packet}${cmdEnd}

  sendRfPacket(packet):
    run: ${cmdStart}rf${cmdMid}${ARGS.packet}${cmdEnd}
