---

# SENSOR 1

${Properties.selfObjectName}.illuminance-1:
  Set main variable - ${Properties.selfObjectName}:
    if:
      - this <= this.illuminance-2
      - ${Properties.light-sensor} != NONE
    set:
      illuminance: this.illuminance-1

${Properties.selfObjectName}.occupancy-1:
  Set main variable:
    set:
      occupancy: this.occupancy-1

${Properties.selfObjectName}.no_occupancy_since-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.no_occupancy_since-2
    set:
      no_occupancy_since: this.no_occupancy_since-1

${Properties.selfObjectName}.linkquality-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.linkquality-2
    set:
      linkquality: this.linkquality-1

${Properties.selfObjectName}.battery-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.battery-2
    set:
      battery: this.battery-1

  Low battery - ${Properties.selfObjectName}:
    if:
      - this <= 40
      - this < ${Properties.selfObjectName}.battery.previousValue
    run:
      - SystemWarn.send('${Properties.selfObjectName}-1 has this.battery-1% battery left!')
      - SystemNotify.send('${Properties.selfObjectName}-1 has this.battery-1% battery left!')

${Properties.selfObjectName}.voltage-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.voltage-2
    set:
      voltage: this.voltage-1

# SENSOR 2

${Properties.selfObjectName}.illuminance-2:
  Set main variable - ${Properties.selfObjectName}:
    if:
      - this <= this.illuminance-1
      - ${Properties.light-sensor} != NONE
    set:
      illuminance: this.illuminance-2

${Properties.selfObjectName}.occupancy-2:
  Set main variable:
    set:
      occupancy: this.occupancy-2

${Properties.selfObjectName}.no_occupancy_since-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.no_occupancy_since-1
    set:
      no_occupancy_since: this.no_occupancy_since-2

${Properties.selfObjectName}.linkquality-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.linkquality-1
    set:
      linkquality: this.linkquality-2

${Properties.selfObjectName}.battery-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.battery-1
    set:
      battery: this.battery-2

${Properties.selfObjectName}.battery:
  Low battery - ${Properties.selfObjectName}:
    if:
      - this <= 40
      - this < ${Properties.selfObjectName}.battery.previousValue
    run:
      - SystemWarn.send('${Properties.selfObjectName}-2 has this.battery-2% battery left!')
      - SystemNotify.send('${Properties.selfObjectName}-2 has this.battery-2% battery left!')

${Properties.selfObjectName}.voltage-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.voltage-1
    set:
      voltage: this.voltage-2

# LIGHT SENSOR

${Properties.light-sensor}.illuminance_lux:
  Sync illuminance - ${Properties.selfObjectName}:
    set:
      ${Properties.selfObjectName}.illuminance: ${Properties.light-sensor}.illuminance_lux
