---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}/status

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:

  ${Properties.mqtt-topic}/status:
    status: ${PARAMS.status}
    volume: ${PARAMS.volume}
