---

${Properties.selfObjectName}.status:

  ON - ${Properties.selfObjectName}:
    if: this is on
    run: SystemNotify.send('${Properties.selfObjectName} is ON')

  PLAYING - ${Properties.selfObjectName}:
    if: this is playing
    run: SystemNotify.send('${Properties.selfObjectName} is PLAYING')

  PAUSED - ${Properties.selfObjectName}:
    if: this is paused
    run: SystemNotify.send('${Properties.selfObjectName} is PAUSED')

  OFF - ${Properties.selfObjectName}:
    if: this is off
    run: SystemNotify.send('${Properties.selfObjectName} is OFF')

  RESET SHAZAM DATA WHEN NOT PLAYING - ${Properties.selfObjectName}:
    if: this is not playing
    set:
      img_background: '-'
      img_cover: '-'
      img_cover_hq: '-'
      artist: '-'
      title: '-'
      genre: '-'
