---

${Properties.selfObjectName}.status:

  TURNED ON - TV OFF - ${Properties.selfObjectName}:
    if:
      - this is on
      - Livingroom-TV.status is off
    run:
      - Livingroom-TV.switchToSmarthome()
      - SystemNotify.send('TV ON (${Properties.selfObjectName} is ON)')

  TURNED ON - TV SWITCH - ${Properties.selfObjectName}:
    if:
      - this is on
      - Livingroom-TV.status is on
      - Livingroom-TV.source is not smarthome
    run:
      - Livingroom-TV.switchToSmarthome()
      - SystemNotify.send('TV switch to SMARTHOME (${Properties.selfObjectName} is ON)')

  TURNED OFF - ${Properties.selfObjectName}:
    if:
      - this is off
      - Livingroom-TV.status is on
      - Livingroom-TV.source is smarthome
    run:
      - Livingroom-TV.off()
      - SystemNotify.send('TV OFF (${Properties.selfObjectName} is OFF)')

  PLAYING - TV OFF - ${Properties.selfObjectName}:
    if:
      - this is playing
      - Livingroom-TV.status is off
    run:
      - Livingroom-TV.switchToSmarthome()
      - SystemNotify.send('TV ON (${Properties.selfObjectName} is ON)')

  PLAYING - TV SWITCH - ${Properties.selfObjectName}:
    if:
      - this is playing
      - Livingroom-TV.status is on
      - Livingroom-TV.source is not smarthome
    run:
      - Livingroom-TV.switchToSmarthome()
      - SystemNotify.send('TV switch to SMARTHOME (${Properties.selfObjectName} is PLAYING)')

  PAUSED - ${Properties.selfObjectName}:
    if: this is paused
    run:
      - SystemNotify.send('${Properties.selfObjectName} is PAUSED')
