---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}/get

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:

  ${Properties.mqtt-topic}/get:
    status: ${PARAMS.status}
    speed: ${PARAMS.speed}
    freq: ${PARAMS.freq}
    offlineSpeed: ${PARAMS.offline-speed}
    offlineFreq: ${PARAMS.offline-freq}
