---

# SENSOR 1

illuminance-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.illuminance-2
    set:
      illuminance: this.illuminance-1

occupancy-1:
  Set main variable:
    set:
      occupancy: this.occupancy-1

no_occupancy_since-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.no_occupancy_since-2
    set:
      no_occupancy_since: this.no_occupancy_since-1

linkquality-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.linkquality-2
    set:
      linkquality: this.linkquality-1

battery-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.battery-2
    set:
      battery: this.battery-1

  Low battery - ${Properties.selfObjectName}:
    if: this <= 40
    run:
      - SystemWarn.send('${Properties.selfObjectName}-1 has this.battery-1% battery left!')
      - SystemNotify.send('${Properties.selfObjectName}-1 has this.battery-1% battery left!')

voltage-1:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.voltage-2
    set:
      voltage: this.voltage-1

# SENSOR 2

illuminance-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.illuminance-1
    set:
      illuminance: this.illuminance-2

occupancy-2:
  Set main variable:
    set:
      occupancy: this.occupancy-2

no_occupancy_since-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.no_occupancy_since-1
    set:
      no_occupancy_since: this.no_occupancy_since-2

linkquality-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.linkquality-1
    set:
      linkquality: this.linkquality-2

battery-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.battery-1
    set:
      battery: this.battery-2

  Low battery - ${Properties.selfObjectName}:
    if: this <= 40
    run:
      - SystemWarn.send('${Properties.selfObjectName}-2 has this.battery-2% battery left!')
      - SystemNotify.send('${Properties.selfObjectName}-2 has this.battery-2% battery left!')

voltage-2:
  Set main variable - ${Properties.selfObjectName}:
    if: this <= this.voltage-1
    set:
      voltage: this.voltage-2
