---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: bluetooth/device/${Properties.mac}

# Known actions and what variables are set by them
actions:
  all:
    mac: ${PARAMS.mac}
    name: ${PARAMS.name}
    last_seen: ${PARAMS.last_seen}

# # Params are not rewritten in the DB if the value isn't changed.
# # This allows them to be written anyway.
# alwaysSetWhenReceived:
#   - event_code
#   - event_name
