---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    angle_x: ${PARAMS.angle_x}
    angle_y: ${PARAMS.angle_y}
    angle_z: ${PARAMS.angle_z}
    angle_x_absolute: ${PARAMS.angle_x_absolute}
    angle_y_absolute: ${PARAMS.angle_y_absolute}
    linkquality: ${PARAMS.linkquality}
    battery: ${PARAMS.battery}
    voltage: ${PARAMS.voltage}
    unknown_data: ${PARAMS.unknown_data}
    angle: ${PARAMS.angle}