---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    battery: ${PARAMS.battery}
    click: ${PARAMS.click}
    linkquality: ${PARAMS.linkquality}
    voltage: ${PARAMS.voltage}

# Params are not rewritten in the DB if the value isn't changed.
# This allows them to be written anyway.
alwaysSetWhenReceived:
  - click
