---

click:
  Clicked the button:
    run: "SystemNotify.send('this.objectName was clicked: this')"

battery:
  Low battery:
    if: this <= 5
    run: SystemWarn.send('this.objectName has this.battery% battery left!')
