---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.params.id}: ${Properties.id}
  - ${PARAMS.result.group.id}: ${Properties.id}

# Take the action param from the event param
actionParam: ${PARAMS.method}

# Known actions and what variables are set by them
actions:
  all:
    muted: ${PARAMS.result.group.muted}
    stream_id: ${PARAMS.result.group.stream_id}

  Group.OnMute:
    muted: ${PARAMS.params.mute}

  Group.OnStreamChanged:
    stream_id: ${PARAMS.params.stream_id}

  Group.OnNameChanged:
    name: ${PARAMS.params.name}