---

jobs:

  # No motion detected for one hour
  - interval: 60
    if:
      - House.presence is true
      - House.lastMotion.timeSince >= 3600
    run:
      - House.allLightsOff()
      - SystemNotify.send('All lights OFF (No house motion for 3600 seconds)')

  # Someone left the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 300
      - ${Properties.door}.contact.timeSince <= House.lastMotion.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'false'
      ${Properties.door}.action: 'exit'

  # Someone entered the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 300
      - ${Properties.door}.contact.timeSince > House.lastMotion.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'true'
      ${Properties.door}.action: 'enter'
