---

jobs:

  # No motion detected for 8 hours
  - interval: 60
    if:
      - House.presence is true
      - House.lastMotion.timeSince >= 28800
    run:
      - House.allLightsOff()
      - SystemNotify.send('No presence (No house motion for 8 hours)')
      - SystemWarn.send('No presence (No house motion for 8 hours)')
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'false'
      House.sleeping: 'false'

  # No motion detected for 2 hours
  - interval: 60
    if:
      - House.presence is true
      - House.sleeping is not true
      - House.lastMotion.timeSince >= 7200
    run:
      - SystemNotify.send('Sleeping (No house motion for 2 hours)')
      - SystemWarn.send('Sleeping (No house motion for 2 hours)')
    set:
      House.sleeping: 'true'

  # Someone left the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 60
      - ${Properties.door}.contact.timeSince <= House.lastMotion.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'false'
      ${Properties.door}.action: 'exit'

  # Someone entered the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 60
      - ${Properties.door}.contact.timeSince > House.lastMotion.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'true'
      ${Properties.door}.action: 'enter'
