---

jobs:

  # No human action for 8 hours and not sleeping - assume no presence
  - interval: 119
    if:
      - House.presence is true
      - House.lastHumanAction.timeSince >= 28800
    run:
      - House.off()
      - SystemNotify.send('No presence (No human action for 8 hours)')
      - SystemWarn.send('No presence (No human action for 8 hours)')
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'false'
      House.sleeping: 'false'

  # No human action for 2 hours - assume sleeping
  - interval: 60
    if:
      - House.presence is true
      - House.sleeping is not true
      - House.lastHumanAction.timeSince >= 7200
    run:
      - SystemNotify.send('Sleeping (No human action for 2 hours)')
      - SystemWarn.send('Sleeping (No human action for 2 hours)')
    set:
      House.sleeping: 'true'

  # Someone left the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 60
      - ${Properties.door}.contact.timeSince <= House.lastHumanAction.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'false'
      ${Properties.door}.action: 'exit'

  # Someone entered the house:
  - interval: 5
    if:
      - House.shouldCheckPresence is true
      - ${Properties.door}.contact is true
      - ${Properties.door}.contact.timeSince >= 60
      - ${Properties.door}.contact.timeSince > House.lastHumanAction.timeSince
    set:
      House.shouldCheckPresence: 'false'
      House.presence: 'true'
      ${Properties.door}.action: 'enter'
