---

functions:

  lightOn():
    runFunctionsAsync:
      - ${Properties.room-1}.lightOn()
      - ${Properties.room-2}.lightOn()
      - ${Properties.room-3}.lightOn()
      - ${Properties.room-4}.lightOn()
      - ${Properties.room-5}.lightOn()
      - ${Properties.room-6}.lightOn()
      - ${Properties.room-7}.lightOn()
      - ${Properties.room-8}.lightOn()
      - ${Properties.room-9}.lightOn()

  lightOff():
    runFunctionsAsync:
      - ${Properties.room-1}.lightOff()
      - ${Properties.room-2}.lightOff()
      - ${Properties.room-3}.lightOff()
      - ${Properties.room-4}.lightOff()
      - ${Properties.room-5}.lightOff()
      - ${Properties.room-6}.lightOff()
      - ${Properties.room-7}.lightOff()
      - ${Properties.room-8}.lightOff()
      - ${Properties.room-9}.lightOff()

  allLightsOff():
    runFunctionsAsync:
      - ${Properties.room-1}.allLightsOff()
      - ${Properties.room-2}.allLightsOff()
      - ${Properties.room-3}.allLightsOff()
      - ${Properties.room-4}.allLightsOff()
      - ${Properties.room-5}.allLightsOff()
      - ${Properties.room-6}.allLightsOff()
      - ${Properties.room-7}.allLightsOff()
      - ${Properties.room-8}.allLightsOff()
      - ${Properties.room-9}.allLightsOff()

  lightOnWhereWindowsAreOpened():
    runFunctionsAsync:
      - ${Properties.room-1}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-2}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-3}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-4}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-5}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-6}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-7}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-8}.forceLightOnIfWindowsAreOpened()
      - ${Properties.room-9}.forceLightOnIfWindowsAreOpened()

  updateDoorsStatus():
    if:
      - ${Properties.room-1}.closedDoor != true
      - ${Properties.room-2}.closedDoor != true
      - ${Properties.room-3}.closedDoor != true
      - ${Properties.room-4}.closedDoor != true
      - ${Properties.room-5}.closedDoor != true
      - ${Properties.room-6}.closedDoor != true
      - ${Properties.room-7}.closedDoor != true
      - ${Properties.room-8}.closedDoor != true
      - ${Properties.room-9}.closedDoor != true
    set:
      closedDoors: 'false'
    elseSet:
      closedDoors: 'true'

  updateWindowsStatus():
    if:
      - ${Properties.room-1}.openWindows != true
      - ${Properties.room-2}.openWindows != true
      - ${Properties.room-3}.openWindows != true
      - ${Properties.room-4}.openWindows != true
      - ${Properties.room-5}.openWindows != true
      - ${Properties.room-6}.openWindows != true
      - ${Properties.room-7}.openWindows != true
      - ${Properties.room-8}.openWindows != true
      - ${Properties.room-9}.openWindows != true
    set:
      openWindows: 'false'
    elseSet:
      openWindows: 'true'

  updateSleepingStatus():
    if:
      - ${Properties.room-1}.sleeping != true
      - ${Properties.room-2}.sleeping != true
      - ${Properties.room-3}.sleeping != true
      - ${Properties.room-4}.sleeping != true
      - ${Properties.room-5}.sleeping != true
      - ${Properties.room-6}.sleeping != true
      - ${Properties.room-7}.sleeping != true
      - ${Properties.room-8}.sleeping != true
      - ${Properties.room-9}.sleeping != true
    set:
      sleeping: 'false'
    elseSet:
      sleeping: 'true'

  offWithoutVacuum():
    runFunctionsAsync:
      - ${Properties.room-1}.off()
      - ${Properties.room-2}.off()
      - ${Properties.room-3}.off()
      - ${Properties.room-4}.off()
      - ${Properties.room-5}.off()
      - ${Properties.room-6}.off()
      - ${Properties.room-7}.off()
      - ${Properties.room-8}.off()
      - ${Properties.room-9}.off()

  off():
    runFunctionsAsync:
      - House.offWithoutVacuum()
      - ${Properties.roborock.object}.home()


  awake():
    runFunctionsAsync:
      - ${Properties.room-1}.awake()
      - ${Properties.room-2}.awake()
      - ${Properties.room-3}.awake()
      - ${Properties.room-4}.awake()
      - ${Properties.room-5}.awake()
      - ${Properties.room-6}.awake()
      - ${Properties.room-7}.awake()
      - ${Properties.room-8}.awake()
      - ${Properties.room-9}.awake()
