---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.name}/window

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:
  ${Properties.name}/window:
    window: ${PARAMS.RAW}
