---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: cec/client/rx/DEBUG
  - ${PARAMS.mqtt-topic}: cec/client/rx/NOTICE
  - ${PARAMS.mqtt-topic}: cec/client/rx/TRAFFIC
  - ${PARAMS.mqtt-topic}: cec/client/rx/UNKNOWN

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:
  cec/client/rx/DEBUG:
    message: ${PARAMS.RAW}

  cec/client/rx/NOTICE:
    message: ${PARAMS.RAW}

  cec/client/rx/TRAFFIC:
    message: ${PARAMS.RAW}

  cec/client/rx/UNKNOWN:
    message: ${PARAMS.RAW}
