---

System.time:
  It's day - ${Properties.selfObjectName}:
    if:
      - this >= ${Properties.selfObjectName}.sunrise
      - this < ${Properties.selfObjectName}.sunset
    set:
      ${Properties.selfObjectName}.state: day

  It's night after midnight - ${Properties.selfObjectName}:
    if:
      - this < ${Properties.selfObjectName}.sunrise
    set:
      ${Properties.selfObjectName}.state: night

  It's night before midnight - ${Properties.selfObjectName}:
    if:
      - this >= ${Properties.selfObjectName}.sunset
    set:
      ${Properties.selfObjectName}.state: night