---

System.time:
  It's day:
    if: this is ${Properties.selfObjectName}.sunrise
    set:
      ${Properties.selfObjectName}.state: day

  It's night:
    if: this is ${Properties.selfObjectName}.sunset
    set:
      ${Properties.selfObjectName}.state: night
