--- # Do stuff when certain variables are changed

# TEMPERATURE

${Properties.temperature.object}.temperature:
  Adjust heating - ${Properties.selfObjectName}:
    run:
      - ${Properties.selfObjectName}.auto()

# CONTROLLER STATUS

${Properties.controller}.status:
  Take controller status - ON - ${Properties.selfObjectName}:
    if: this is on
    set:
      ${Properties.selfObjectName}.status: 'on'

  Take controller status - OFF - ${Properties.selfObjectName}:
    if: this is off
    set:
      ${Properties.selfObjectName}.status: 'off'

# WINDOWS

House.openWindows:
  On status change - ${Properties.selfObjectName}:
    run:
      - ${Properties.selfObjectName}.auto()

# PRESENCE

House.presence:
  On status change - ${Properties.selfObjectName}:
    run:
      - ${Properties.selfObjectName}.auto()

# SLEEPING

House.sleeping:
  On status change - ${Properties.selfObjectName}:
    run:
      - ${Properties.selfObjectName}.auto()
