--- # Do stuff when certain variables are changed

Livingroom-Button.click:
  asdf:
    if:
      - this is double
    run:
      - ${Properties.selfObjectName}.auto()

# TEMPERATURE

${Properties.temperature.object}.temperature:

  Turn on - ${Properties.selfObjectName}:
    run:
      - ${Properties.selfObjectName}.auto()

# CONTROLLER STATUS

${Properties.controller}.status:
  Take controller status - ON - ${Properties.selfObjectName}:
    if:
      - this is on
    set:
      ${Properties.selfObjectName}.status: 'on'

  Take controller status - OFF - ${Properties.selfObjectName}:
    if:
      - this is off
    set:
      ${Properties.selfObjectName}.status: 'off'

# WINDOWS

House.openWindows:

  Opening windows - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.selfObjectName}.status is not off
    run:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('${Properties.selfObjectName} OFF (Opened windows)')
      - SystemWarn.send('${Properties.selfObjectName} OFF (Opened windows)')

  Closing windows - ${Properties.selfObjectName}:
    if:
      - this is false
    run:
      - ${Properties.selfObjectName}.auto()

# PRESENCE

House.presence:
  When house is empty - turn off heating - ${Properties.selfObjectName}:
    if:
      - this is false
      - ${Properties.selfObjectName}.status is not off
    run:
      - ${Properties.selfObjectName}.off()
      - SystemWarn.send('${Properties.selfObjectName} OFF (Empty house)')

  When house is populated - ${Properties.selfObjectName}:
    if:
      - this is true
    run:
      - ${Properties.selfObjectName}.auto()
      - SystemWarn.send('Presence detected!')
      - SystemNotify.send('Presence detected!')

# SLEEPING

House.sleeping:

  Sleeping - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.selfObjectName}.status is not off
    run:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('${Properties.selfObjectName} OFF (Sleeping)')
      - SystemWarn.send('${Properties.selfObjectName} OFF (Sleeping)')

  Awake - ${Properties.selfObjectName}:
    if:
      - this is false
    run:
      - ${Properties.selfObjectName}.auto()
