---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    battery: ${PARAMS.battery}
    contact: ${PARAMS.contact}
    linkquality: ${PARAMS.linkquality}
    voltage: ${PARAMS.voltage}
