---

cmd: 'mosquitto_pub -h mqtt -t "cec/client/tx" -m'

functions:

  on():
    run: ${cmd} 'on 0'

  off():
    run: ${cmd} 'standby 0'

  switchToSmarthome():
    run: ${cmd} 'as';${cmd} 'p 0 3'

  switchToGaming():
    run: ${cmd} 'on';${cmd} 'p 0 1'

  sendRaw(command):
    run: ${cmd} '${ARGS.command}''
