---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    current: ${PARAMS.current}
    energy: ${PARAMS.energy}
    linkquality: ${PARAMS.linkquality}
    power: ${PARAMS.power}
    status: ${PARAMS.state}
    voltage: ${PARAMS.voltage}
    child_lock: ${PARAMS.child_lock}
    indicator_mode: ${PARAMS.indicator_mode}
    linkquality: ${PARAMS.linkquality}
    last-input-time: foo

normalize-params:
  all:
    status:
      'ON': 'on'
      'OFF': 'off'

alwaysSetWhenReceived:
  - last-input-time