---

functions:

  on():
    runFunctions:
      - ${Properties.broadlinkController}.sendIrPacket('JgDKAJCTEzUTERM1EzUTERMREzUTERMREzUTEhMREzUTNRMREzUTNRMRExETNRM1EzUTNRM1ExISNRM1ExISEhMRExETERMRExETERMSExETERMRExETNRM1EzUTNRM1EzUTNRM1Ea2SkBM1ExETNRM1ExETEhI1ExITERM1ExETERM1EzUTERM1EzYSEhISEzUTNRM1EjYSNhISEzUTNRMREhISEhISEhISExETEhISEhISEhISEhITETcRNxI2ETYTNRM1EzUTNREADQUAAAAAAAAAAAAAAAAAAA==')
    set:
      status: 'on'

  off():
    runFunctions:
      - ${Properties.broadlinkController}.sendIrPacket('JgDKAI+SEzUTEhI2EzUTERMREzUTERMREzUTERMSEjUTNRMSEjYTERM1EzUTNRM1ExETNRM1EzUTEhISEhITERM1ExETERM1EzUTNRMRExETEhISEhITERMRExETNRM1EzUTNRM1Ea6RkRI2EhISNhI2EhMRExI2EhITERM1EhISEhI2EjYSEhM2ERMTNRI2EjYSNhISEjYSNhI2ExETERMSEhISNhISExETNRM1EzUTERMRExETEhISExETERMREzUTNRM1EzUTNREADQUAAAAAAAAAAAAAAAAAAA==')
    set:
      status: 'off'

  swingToggle():
    runFunctions:
      - ${Properties.broadlinkController}.sendIrPacket('JgDKAJKPEzYSEhM1EzUTERMREzUTERMREzUTERMSEjUTNRMSEzUTERM1EzUTERM1ExETNRM1EzUUERMREzUTERM1ExETERM1EzUTNRMSEhITERMRExETERMRExETNRM1EzUTNRM1FKuSkBM1ExETNRM1ExITERM0FBETERM1ExETERM1EzUTERM1FBETNRM1ExETNRMREzUUNBM1FBESEhM1ExETNhIRExETNRM1EzUTERMSEhITERMRExETERMREzUTNRM1FDQTNRQADQUAAAAAAAAAAAAAAAAAAA==')

  ledToggle():
    runFunctions:
      - ${Properties.broadlinkController}.sendIrPacket('JgDKAJOPEzMVEhM1EzUTERM1ExETNRMREzUTERMSEzQUERM1ExETNRM1EzUTNRMREzUTERM1FBETERMRExETNRMREzUTEhM1ExETNRMRExETNRMREzUTEhM0FBETNRM2EhETNRMRE6uTjxQ0FBETNRM1ExETNRMREzUTEhI1ExITERM1ExETNRMREzUTNRM1EzUTERM1ExISNhMRExETERMREzUTERM1FBETNRMREzUTERMREzUTERM1FBETNRMREzUTNRMREzUTEREADQUAAAAAAAAAAAAAAAAAAA==')
