---

${Properties.selfObjectName}.battery:
  Low battery - ${Properties.selfObjectName}:
    if:
      - this <= 40
      - this < ${Properties.selfObjectName}.battery.previousValue
    run:
      - SystemWarn.send('${Properties.selfObjectName} has this.battery% battery left!')
      - SystemNotify.send('${Properties.selfObjectName} has this.battery% battery left!')

${Properties.selfObjectName}.click:
  Sync with another button - ${Properties.selfObjectName}:
    if:
      - ${Properties.sync-with} is not NONE
    set:
      ${Properties.sync-with}.click: ${Properties.selfObjectName}.click
