---

jobs:

  # Ledstrip - dim light
  - interval: 5
    if:
      - ${Properties.light.object}.status is on
      - ${Properties.ledstrip.object}.status is on
      - ${Properties.ledstrip.object}.brightness is 100
      - ${Properties.ledstrip.motion.object}.occupancy is false
      - ${Properties.ledstrip.motion.object}.occupancy.timeSince >= 300
    run:
      - ${Properties.ledstrip.object}.brightness('50')
      - SystemNotify.send('${Properties.ledstrip.object} dimmed (No motion for 300s)')

  # NO MOTION DETECTED - LAST MOTION IS LOCAL

  # Primary Light
  - interval: 5
    if:
      - ${Properties.light.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.off-when-no-motion-for-X-seconds-current-location}
    run:
      - ${Properties.selfObjectName}.lightOff()
      - SystemNotify.send('${Properties.light.object} OFF (No motion for ${Properties.light.off-when-no-motion-for-X-seconds-current-location} seconds - current location)')

  # Secondary Light
  - interval: 5
    if:
      - ${Properties.light.secondary.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - House.lastMotionLocation is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.secondary.off-when-no-motion-for-X-seconds-current-location}
    run:
      - ${Properties.selfObjectName}.secondaryLightOff()
      - SystemNotify.send('${Properties.light.secondary.object} OFF (No motion for ${Properties.light.secondary.off-when-no-motion-for-X-seconds-current-location} seconds - current location)')

  # Ledstrip
  - interval: 5
    if:
      - ${Properties.ledstrip.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.ledstrip.off-when-no-motion-for-X-seconds-current-location}
    run:
      - ${Properties.ledstrip.object}.off()
      - SystemNotify.send('${Properties.ledstrip.object} OFF (No motion for ${Properties.light.off-when-no-motion-for-X-seconds-current-location} seconds - current location)')

  # NO MOTION DETECTED - PREV MOTION IS LOCAL

  # Primary Light
  - interval: 4
    if:
      - ${Properties.light.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation.previousValue is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.off-when-no-motion-for-X-seconds-prev-location}
    run:
      - ${Properties.selfObjectName}.lightOff()
      - SystemNotify.send('${Properties.light.object} OFF (No motion for ${Properties.light.off-when-no-motion-for-X-seconds-prev-location} seconds - prev location)')

  # Secondary Light
  - interval: 4
    if:
      - ${Properties.light.secondary.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - House.lastMotionLocation.previousValue is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.secondary.off-when-no-motion-for-X-seconds-prev-location}
    run:
      - ${Properties.selfObjectName}.secondaryLightOff()
      - SystemNotify.send('${Properties.light.secondary.object} OFF (No motion for ${Properties.light.secondary.off-when-no-motion-for-X-seconds-prev-location} seconds - prev location)')

  # Ledstrip
  - interval: 4
    if:
      - ${Properties.ledstrip.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation.previousValue is '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.ledstrip.off-when-no-motion-for-X-seconds-prev-location}
    run:
      - ${Properties.ledstrip.object}.off()
      - SystemNotify.send('${Properties.ledstrip.object} OFF (No motion for ${Properties.ledstrip.off-when-no-motion-for-X-seconds-prev-location} seconds - prev location)')

  # NO MOTION DETECTED - LAST & PREV MOTION IS NOT LOCAL

  # Primary Light
  - interval: 3
    if:
      - ${Properties.light.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation is not '${Properties.name}'
      - House.lastMotionLocation.previousValue is not '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.off-when-no-motion-for-X-seconds-old-location}
    run:
      - ${Properties.selfObjectName}.lightOff()
      - SystemNotify.send('${Properties.light.object} OFF (No motion for ${Properties.light.off-when-no-motion-for-X-seconds-old-location} seconds - old location)')

  # Secondary Light
  - interval: 3
    if:
      - ${Properties.light.secondary.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - House.lastMotionLocation is not '${Properties.name}'
      - House.lastMotionLocation.previousValue is not '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.light.secondary.off-when-no-motion-for-X-seconds-old-location}
    run:
      - ${Properties.selfObjectName}.secondaryLightOff()
      - SystemNotify.send('${Properties.light.secondary.object} OFF (No motion for ${Properties.light.secondary.off-when-no-motion-for-X-seconds-old-location} seconds - old location)')

  # Ledstrip
  - interval: 3
    if:
      - ${Properties.ledstrip.object}.status is on
      - ${Properties.motion.object}.occupancy is false
      - ${Properties.selfObjectName}.forceLightOn is not true
      - House.lastMotionLocation is not '${Properties.name}'
      - House.lastMotionLocation.previousValue is not '${Properties.name}'
      - ${Properties.motion.object}.occupancy.timeSince >= ${Properties.ledstrip.off-when-no-motion-for-X-seconds-old-location}
    run:
      - ${Properties.ledstrip.object}.off()
      - SystemNotify.send('${Properties.ledstrip.object} OFF (No motion for ${Properties.ledstrip.off-when-no-motion-for-X-seconds-old-location} seconds - old location)')

  # STOP IGNORING MOVEMENT AFTER X SECONDS
  - interval: 5
    if:
      - ${Properties.selfObjectName}.ignoreMotion is true
      - ${Properties.selfObjectName}.ignoreMotion.timeSince >= ${Properties.motion.stop-ignoring-motion-after-X-seconds}
    set:
      ${Properties.selfObjectName}.ignoreMotion: 'false'

  # STOP FORCED ON/OFF LIGHT

  # Primary Light Force OFF
  - interval: 5
    if:
      - ${Properties.selfObjectName}.forceLightOff is true
      - ${Properties.selfObjectName}.forceLightOff.timeSince >= ${Properties.light.force-light-off-seconds}
    set:
      ${Properties.selfObjectName}.forceLightOff: 'false'
    run:
      - SystemNotify.send('${Properties.selfObjectName} deactivated force light off')

  # Primary Light Force ON
  - interval: 5
    if:
      - ${Properties.selfObjectName}.forceLightOn is true
      - ${Properties.selfObjectName}.forceLightOn.timeSince >= ${Properties.light.force-light-on-seconds}
    set:
      ${Properties.selfObjectName}.forceLightOn: 'false'
    run:
      - SystemNotify.send('${Properties.selfObjectName} deactivated force light on')
