---

functions:

  lightOn():
    if:
      - ${Properties.light.object}.status not in ['on','offline']
    runFunctions:
      - ${Properties.light.object}.on()
      - ${Properties.light.object}.temperature('${Properties.light.temperature}')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
    set:
      forceLightOff: 'false'

  secondaryLightOn():
    if:
      - ${Properties.light.secondary.object}.status not in ['on','offline']
    runFunctions:
      - ${Properties.light.secondary.object}.on()
      - ${Properties.light.secondary.object}.temperature('${Properties.light.secondary.temperature}')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')

  lightOff():
    if:
      - ${Properties.light.object}.status is 'on'
    runFunctions:
      - ${Properties.light.object}.off()
    set:
      forceLightOn: 'false'

  secondaryLightOff():
    if:
      - ${Properties.light.secondary.object}.status is 'on'
    runFunctions:
      - ${Properties.light.secondary.object}.off()

  allLightsOff():
    runFunctionsAsync:
      - ${Properties.selfObjectName}.lightOff()
      - ${Properties.selfObjectName}.secondaryLightOff()
      - ${Properties.ledstrip.object}.off()

  off():
    runFunctionsAsync:
      - ${Properties.selfObjectName}.lightOff()
      - ${Properties.selfObjectName}.secondaryLightOff()
      - ${Properties.ledstrip.object}.off()
      - ${Properties.tv.object}.off()
      - ${Properties.tv.audio-system.object}.off()

  lightWarn():
    if: ${Properties.light.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.object}.on()
      - ${Properties.light.object}.rgb('16748687')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
      - System.sleep('0.4')
      - ${Properties.light.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.on('0.2')
    set:
      forceLightOn: 'true'

  lightWarnShort():
    if: ${Properties.light.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.object}.on()
      - ${Properties.light.object}.rgb('16748687')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
      - System.sleep('1')

  lightSuccess():
    if: ${Properties.light.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.object}.on()
      - ${Properties.light.object}.rgb('4390713')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
      - System.sleep('0.4')
      - ${Properties.light.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.selfObjectName}.lightUnwarn()

  lightSuccessShort():
    if: ${Properties.light.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.object}.on()
      - ${Properties.light.object}.rgb('4390713')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
      - System.sleep('1')
      - ${Properties.selfObjectName}.lightUnwarn()

  lightUnwarn():
    if: ${Properties.light.object}.status is on
    runFunctions:
      - ${Properties.light.object}.temperature('${Properties.light.temperature}')
      - ${Properties.light.object}.brightness('${Properties.light.brightness}')
    set:
      forceLightOn: 'false'

  secondaryLightWarn():
    if: ${Properties.light.secondary.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.secondary.object}.on()
      - ${Properties.light.secondary.object}.rgb('16748687')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.on('0.2')

  secondaryLightWarnShort():
    if: ${Properties.light.secondary.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.secondary.object}.on()
      - ${Properties.light.secondary.object}.rgb('16748687')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')
      - System.sleep('1')

  secondaryLightSuccess():
    if: ${Properties.light.secondary.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.secondary.object}.on()
      - ${Properties.light.secondary.object}.rgb('4390713')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.on('0.2')
      - System.sleep('0.4')
      - ${Properties.light.secondary.object}.off('0.2')
      - System.sleep('0.4')
      - ${Properties.selfObjectName}.secondaryLightUnwarn()

  secondaryLightSuccessShort():
    if: ${Properties.light.secondary.object}.status in ['on','off']
    runFunctions:
      - ${Properties.light.secondary.object}.on()
      - ${Properties.light.secondary.object}.rgb('4390713')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')
      - System.sleep('1')
      - ${Properties.selfObjectName}.secondaryLightUnwarn()

  secondaryLightUnwarn():
    if: ${Properties.light.secondary.object}.status is on
    runFunctions:
      - ${Properties.light.secondary.object}.temperature('${Properties.light.secondary.temperature}')
      - ${Properties.light.secondary.object}.brightness('${Properties.light.secondary.brightness}')

  forceLightOnIfWindowsAreOpened():
    if:
      - ${Properties.selfObjectName}.openWindows is true
      - ${Properties.light.object}.status in ['on','off']
    set:
      forceLightOn: 'true'
    runFunctions:
      - ${Properties.selfObjectName}.lightOn()
      - SystemWarn.send('Light ON (Window is opened @ ${Properties.selfObjectName})')
      - SystemNotify.send('Light ON (Window is opened @ ${Properties.selfObjectName})')
