---

name: NONE

motion:
  object: NONE
  stop-ignoring-motion-at: '12:00'
  stop-ignoring-motion-after-X-seconds: 28800
  trigger-presence: 'false'

button:
  object: NONE

light:
  object: NONE
  brightness: 100
  temperature: 3500
  on-by-motion-when-lux-below: 15
  on-duration-when-plex-stopped: 20000
  dim-level-when-plex-paused: 5
  dim-duration-when-plex-paused: 1000
  off-when-no-motion-for-X-seconds-current-location: 3600
  off-when-no-motion-for-X-seconds-prev-location: 120
  off-when-no-motion-for-X-seconds-old-location: 5
  off-when-lux-over: 200

  secondary:
    object: NONE
    brightness: 50
    temperature: 2700
    off-when-no-motion-for-X-seconds: 3600
    off-when-lux-over: 200

door:
  object: NONE

plex:
  object: NONE
  user: NONE
  device: NONE

roborock:
  object: NONE
  local-zone: NONE

tv:
  object: NONE

  audio-system:
    object: NONE

water-sensor:
  object: NONE

