---

jobs:

  # Delayed status
  - interval: 1
    if:
      - ${Properties.selfObjectName}.status == paused
      - ${Properties.selfObjectName}.status != ${Properties.selfObjectName}.statusDelayed
      - ${Properties.selfObjectName}.status.timeSince >= 4
    set:
      ${Properties.selfObjectName}.statusDelayed: ${Properties.selfObjectName}.status
