---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

# Known actions and what variables are set by them
actions:
  all:
    battery: ${PARAMS.battery}
    humidity: ${PARAMS.humidity}
    linkquality: ${PARAMS.linkquality}
    pressure: ${PARAMS.pressure}
    temperature: ${PARAMS.temperature}
    voltage: ${PARAMS.voltage}
