---

# How to recognize the request
recognize-by-comparing:
  - ${PARAMS.mqtt-topic}: ${Properties.mqtt-topic}

actionParam: ${PARAMS.mqtt-topic}

# Known actions and what variables are set by them
actions:
  ${Properties.mqtt-topic}:
    claps: ${PARAMS.claps}
    time: ${PARAMS.time}
