--- # Do stuff when certain variables are changed

House.presence:
  Empty house - ${Properties.selfObjectName}:
    if:
      - this is false
      - ${Properties.sync-with} is NONE
    run:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('Turned ${Properties.selfObjectName} OFF (Empty house)')

  Presence detected - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.sync-with} is NONE
    run:
      - ${Properties.selfObjectName}.on()
      - SystemNotify.send('Turned ${Properties.selfObjectName} ON (Presence detected)')

${Properties.room}.lastHumanAction:
  Turn on when motion detected - ${Properties.selfObjectName}:
    if:
      - ${Properties.selfObjectName}.status is not on
      - House.sleeping is false
      - House.presence is true
    run:
      - ${Properties.selfObjectName}.on()
      - SystemNotify.send('Turned ${Properties.selfObjectName} ON (Motion in ${Properties.room})')
    set:
      status: 'on'

House.sleeping:
  Awake - ${Properties.selfObjectName}:
    if:
      - this is false
      - ${Properties.sync-with} is NONE
    run:
      - ${Properties.selfObjectName}.on()
      - SystemNotify.send('Turned ${Properties.selfObjectName} ON (Awake)')

  Sleeping - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.sync-with} is NONE
    run:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('Turned ${Properties.selfObjectName} OFF (Sleeping)')

${Properties.sync-with}.status:
  turned on - ${Properties.selfObjectName}:
    if:
      - this is on
    run:
      - ${Properties.selfObjectName}.on()
      - SystemNotify.send('Turned ${Properties.selfObjectName} ON (synced ${Properties.sync-with})')
    set:
      status: 'on'

  turned off - ${Properties.selfObjectName}:
    if:
      - this is off
    run:
      - ${Properties.selfObjectName}.off()
      - SystemNotify.send('Turned ${Properties.selfObjectName} OFF (synced ${Properties.sync-with})')
    set:
      status: 'off'
