---

name: NONE

heating: NONE

motion:
  object: NONE
  stop-ignoring-motion-at: '12:00'
  stop-ignoring-motion-after-X-seconds: 28800
  trigger-presence: 'false'
  ignored-motion-means-sleeping: 'false'

button:
  object: NONE
  toggle:
    triple-click: NONE

clapper:
  object: NONE

diffuser:
  object: NONE

purifier:
  object: NONE

airpurifier:
  object: NONE

light:
  object: NONE
  brightness: 100
  temperature: 3500
  on-by-motion-when-lux-below: 15
  on-duration-when-plex-stopped: 10000
  on-while-door-closed: 'false'
  off-when-no-motion-for-X-seconds-current-location: 3600
  off-when-no-motion-for-X-seconds-prev-location: 120
  off-when-no-motion-for-X-seconds-old-location: 5
  off-when-lux-over: 200
  force-light-off-seconds: 1800
  force-light-on-seconds: 3600

  secondary:
    object: NONE
    brightness: 50
    mid-brightness: 50
    temperature: 2700
    off-when-no-motion-for-X-seconds-current-location: 7200
    off-when-no-motion-for-X-seconds-prev-location: 240
    off-when-no-motion-for-X-seconds-old-location: 10
    off-when-lux-over: 200

  other-1: NONE
  other-2: NONE
  other-3: NONE

  night:
    object: NONE

ledstrip:
  object: NONE
  off-when-no-motion-for-X-seconds-current-location: 3600
  off-when-no-motion-for-X-seconds-prev-location: 120
  off-when-no-motion-for-X-seconds-old-location: 5

  motion:
    object: NONE

door:
  object: NONE

window:
  object: NONE

window-2:
  object: NONE

plex:
  object: NONE

roborock:
  object: NONE
  local-zone: NONE

tv:
  object: NONE

  audio-system:
    object: NONE

turntable:
  object: NONE

laptop:
  object: NONE

water-sensor:
  object: NONE

air-seal-rooms:
  room-1: NONE
  room-2: NONE
  room-3: NONE
  room-4: NONE
