---

functions:

  on():
    run: ${Base.paths.modules}/wakeonlan ${Properties.mac}
    set:
      status: 'on'

  getStatus():
    run: ping -W 1 -c 1 ${Properties.ip} | grep '1 received' | wc -l
    if: ${RESPONSE.output} is 1
    set:
      status: 'on'
    elseSet:
      status: 'off'

  getStatusByCron():
    run: ping -W 1 -c 1 ${Properties.ip} | grep '1 received' | wc -l
    if: ${RESPONSE.output} is 1
    set 3rd time:
      status: 'on'
    elseSet 3rd time:
      status: 'off'
