---

cmd: mosquitto_pub -h mqtt -t "service/python-miio/tx" -m "miiocli airpurifiermiot --ip ${Properties.ip} --token ${Properties.token}

functions:

  on():
    run: ${cmd} on"

  off():
    run: ${cmd} off"

  # true/false
  set_buzzer(boolean):
    run: ${cmd} set_buzzer ${ARGS.boolean}"

  # true/false
  set_child_lock(boolean):
    run: ${cmd} set_child_lock ${ARGS.boolean}"

  # 1/2/3
  set_fan_level(number):
    run: ${cmd} set_fan_level ${ARGS.number}"

  # 0-14
  set_favorite_level(number):
    run: ${cmd} set_favorite_level ${ARGS.number}"

  # 300-2300 (steps of 10)
  set_favorite_rpm(number):
    run: ${cmd} set_favorite_rpm ${ARGS.number}"

  # true/false
  set_led(boolean):
    run: ${cmd} set_led ${ARGS.boolean}"

  # bright/dim/off
  set_led_brightness(mode):
    runIf:
      - ${Properties.selfObjectName}.led_brightness is not '${ARGS.mode}'
    run: ${cmd} set_led_brightness ${ARGS.mode}"

  # auto/fan/favorite/silent
  set_mode(mode):
    runIf:
      - ${Properties.selfObjectName}.mode is not '${ARGS.mode}'
    run: ${cmd} set_mode ${ARGS.mode}"

  getStatus():
    run: ${cmd} status"
