--- # Do stuff when certain variables are changed

House.openWindows:
  Opened window - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.selfObjectName}.status is on
    run:
      - ${Properties.selfObjectName}.set_mode('silent')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('off')
      - SystemNotify.send('${Properties.selfObjectName} SILENT (Opened Window)')

  Closed windows - ${Properties.selfObjectName}:
    if:
      - this is false
      - House.sleeping is false
      - House.presence is true
    run:
      - ${Properties.selfObjectName}.set_mode('auto')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('dim')
      - SystemNotify.send('${Properties.selfObjectName} AUTO (Closed Windows)')

House.sleeping:
  Sleeping - ${Properties.selfObjectName}:
    if:
      - this is true
      - ${Properties.selfObjectName}.status is on
    run:
      - ${Properties.selfObjectName}.set_mode('silent')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('off')
      - SystemNotify.send('${Properties.selfObjectName} SILENT (Sleeping)')

  Awake - ${Properties.selfObjectName}:
    if:
      - this is false
      - House.openWindows is false
      - House.presence is true
    run:
      - ${Properties.selfObjectName}.set_mode('auto')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('dim')
      - SystemNotify.send('${Properties.selfObjectName} AUTO (Awake)')

House.presence:
  Empty house - ${Properties.selfObjectName}:
    if:
      - this is false
      - ${Properties.selfObjectName}.status is on
    run:
      - ${Properties.selfObjectName}.set_mode('silent')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('off')
      - SystemNotify.send('${Properties.selfObjectName} SILENT (Empty house)')

  Presence detected - ${Properties.selfObjectName}:
    if:
      - this is true
      - House.openWindows is false
      - House.sleeping is false
    run:
      - ${Properties.selfObjectName}.set_mode('auto')
      - System.sleep('1')
      - ${Properties.selfObjectName}.set_led_brightness('dim')
      - SystemNotify.send('${Properties.selfObjectName} AUTO (Presence detected)')

