---

battery:
  Low battery - ${Properties.selfObjectName}:
    if: this <= 40
    run:
      - SystemWarn.send('${Properties.selfObjectName} has this.battery% battery left!')
      - SystemNotify.send('${Properties.selfObjectName} has this.battery% battery left!')
